export const carBodies = [
    "Hatchback",
    "Convertible",
    "Sedan",
    "Coupe",
    "Minivan",
    "SUV",
    "Van",
    "Wagon",
    // "Cargo Van",
    // "Ext Cargo Minivan",
    // "Ext Cargo Van",
    // "Ext Van",
    // "Ext Minivan",
    // "Passenger Van",
    // "Truck (Access Cab)",
    // "Truck (Cab Plus)",
    // "Truck (Club Cab)",
    // "Truck (Crew Cab)",
    // "Truck (CrewMax)",
    // "Truck (Double Cab)",
    // "Truck (Extended Cab)",
    // "Truck (King Cab)",
    // "Truck (Mega Cab)",
    // "Truck (Quad Cab)",
    // "Truck (Regular Cab)",
    // "Truck (SuperCab)",
    // "Truck (SuperCrew)",
    // "Truck (Xtracab)",
    // "Unknown",
];
